#!/bin/bash
if [ "$EUID" -ne "0" ]; then
	echo "must be run as superuser"
	exit 1
fi
cp volume-control-panel@.service /usr/lib/systemd/system
cp 100-volume-control-panel.rules /usr/lib/udev/rules.d
cp volume-control-panel-interpreter /usr/bin
